" Generated by vim-plug
" Fri Mar  8 13:48:15 2024
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['editorconfig-vim'].commit = '30ddc057f71287c3ac2beca876e7ae6d5abe26a0'
silent! let g:plugs['fzf'].commit = '3dd42f5aa2d7fc6f508f2b21408730a8678c0a19'
silent! let g:plugs['fzf.vim'].commit = '8ea9574b3ebdc44fbe3dc6381a13f9ce0c290e2f'
silent! let g:plugs['matchit'].commit = '2275d88a6be5759103db1b3db331594e043b58d6'
silent! let g:plugs['molokai'].commit = 'c67bdfcdb31415aa0ade7f8c003261700a885476'
silent! let g:plugs['nerdtree'].commit = 'fc85a6f07c2cd694be93496ffad75be126240068'
silent! let g:plugs['undotree'].commit = '9dbbf3b7d19dda0d22ceca461818e4739ad8154d'
silent! let g:plugs['vim-commentary'].commit = 'e87cd90dc09c2a203e13af9704bd0ef79303d755'
silent! let g:plugs['vim-easymotion'].commit = 'b3cfab2a6302b3b39f53d9fd2cd997e1127d7878'
silent! let g:plugs['vim-fugitive'].commit = '8376227c9d5f9cfdc85a9b228997a1644176eb37'
silent! let g:plugs['vim-hcl'].commit = '1e1116c17a5774851360ea8077f349e36fc733c1'
silent! let g:plugs['vim-indent-object'].commit = '5c5b24c959478929b54a9e831a8e2e651a465965'
silent! let g:plugs['vim-paragraph-motion'].commit = '2f6b36670327952b0bcc6915f4947feb85977af3'
silent! let g:plugs['vim-signify'].commit = '7d538b77a5a8806e344b057f8846f6d0c035efa9'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vim-tmux-navigator'].commit = 'cdd66d6a37d991bba7997d593586fc51a5b37aa8'
silent! let g:plugs['vim-unimpaired'].commit = '6d44a6dc2ec34607c41ec78acf81657248580bf1'
silent! let g:plugs['vim-which-key'].commit = '470cd19ce11b616e0640f2b38fb845c42b31a106'

PlugUpdate!

