" Generated by vim-plug
" Mon 12 Jul 2021 02:37:52 AM EDT
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['molokai'].commit = 'c67bdfcdb31415aa0ade7f8c003261700a885476'
silent! let g:plugs['vim-easymotion'].commit = 'd75d9591e415652b25d9e0a3669355550325263d'
silent! let g:plugs['vim-surround'].commit = 'f51a26d3710629d031806305b6c8727189cd1935'
silent! let g:plugs['vim-tmux-navigator'].commit = '0cabb1ef01af0986b7bf6fb7acf631debdbbb470'

PlugUpdate!

